[package]
name = "percos"
version = "2.0.0"
authors = ["ThePerkinrex"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.4"
spin = "0.4.8"
multiboot2 = "0.1.0"
cpuio = "*"
bitflags = "0.9.1"
x86_64 = "0.1.2"
